### ISSUE TITLE
issue can't convert Time into String

### ISSUE THREAD

**Issue by lothar59** [zdennis/ar-extensions#15]
I have this issue when trying to create a new record. I'm using rails 2.3.4

> > columns = [:libelle]
> > => [:libelle]
> > values = ["russe"]
> > => ["russe"]
> > Langue.import columns, values
> > TypeError: can't convert Time into String
> >     from /home/thomas/.rvm/gems/ruby-1.8.7-p352/gems/ar-extensions-0.9.5/lib/ar-extensions/import.rb:319:in `<<'
> >     from /home/thomas/.rvm/gems/ruby-1.8.7-p352/gems/ar-extensions-0.9.5/lib/ar-extensions/import.rb:319:in`add_special_rails_stamps'
> >     from /home/thomas/.rvm/gems/ruby-1.8.7-p352/gems/ar-extensions-0.9.5/lib/ar-extensions/import.rb:319:in `each'
> >     from /home/thomas/.rvm/gems/ruby-1.8.7-p352/gems/ar-extensions-0.9.5/lib/ar-extensions/import.rb:319:in`add_special_rails_stamps'
> >     from /home/thomas/.rvm/gems/ruby-1.8.7-p352/gems/ar-extensions-0.9.5/lib/ar-extensions/import.rb:311:in `each_pair'
> >     from /home/thomas/.rvm/gems/ruby-1.8.7-p352/gems/ar-extensions-0.9.5/lib/ar-extensions/import.rb:311:in`add_special_rails_stamps'
> >     from /home/thomas/.rvm/gems/ruby-1.8.7-p352/gems/ar-extensions-0.9.5/lib/ar-extensions/import.rb:205:in `import'
> >     from (irb):7

any ideas ?

**Comment by zdennis** [comment]
@lothar59, what version of Rails/ActiveRecord are using?

**Comment by lothar59** [comment]
hum I have both activerecord (3.1.1, 2.3.4), but I'm guessing that If I'm using rails 2.3.4 then I'm using also activerecord 2.3.4. Am I guessing wrong ? I have this in my environment file : RAILS_GEM_VERSION = '2.3.4'

EDIT : hum and rails I have 2.3.4
